default: &default
  adapter: postgresql
  encoding: utf-8
  host: localhost
  username: shine
  password: shine
  pool: 5
development:
  <<: *default
  database: prospect_development

test:
  <<: *default
  database: prospect_test

production:
  <<: *default
  database: prospect_production
  username: mantli
  password: <%= ENV['EMAIR_DATABASE_PASSWORD'] %>

