# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f55af3011dbff626a7e53b92a6682f52731b10b9d26430848ed9e21482a49fc5c4dba428d8fa9705bfe5f69d537229acb606b6b70143170f151b16645418ec16

test:
  secret_key_base: f49dd11b33ca3c8d77f805736f51341c97eb36ef1257e08868aa2e0212a2f61f20f589c7640ea1eb9de678cb32454b4f912472abd7196284638624b253c6d7ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
